import { Injectable } from '@angular/core';
import { CoreDatabaseService } from '../database/core-database.service';
import { SecurityService } from '../security/security.service';
import { SchemaManagerService } from '../database/schema-manager.service';

/**
 * Manages the import, export, and destruction of the entire OS ecosystem.
 * Enables local-first portability ensuring the user owns their data.
 */
@Injectable({
  providedIn: 'root'
})
export class SystemPortabilityService {

  constructor(
    private readonly dbEngine: CoreDatabaseService,
    private readonly securityService: SecurityService,
    private readonly schemaManager: SchemaManagerService
  ) { }

  /**
   * Exports the entire database (OS tables + Plugin tables) into a serialized JSON string.
   * @returns A JSON string representing the entire application state.
   */
  async exportEcosystem(): Promise<string> {
    if (!this.securityService.isVaultUnlocked()) {
      throw new Error('[Portability] Cannot export data while the vault is locked.');
    }

    const exportData: Record<string, any[]> = {};
    const tables = this.dbEngine.tables;

    for (const table of tables) {
      exportData[table.name] = await table.toArray();
    }

    console.log(`[Portability] Successfully exported ${tables.length} tables.`);
    return JSON.stringify(exportData);
  }

  /**
   * Imports a previously exported ecosystem state, completely overwriting current data.
   * Wrapped in a transaction to prevent data corruption if the import fails midway.
   * @param jsonString The JSON string generated by exportEcosystem().
   */
  async importEcosystem(jsonString: string): Promise<void> {
    if (!this.securityService.isVaultUnlocked()) {
      throw new Error('[Portability] Cannot import data while the vault is locked.');
    }

    try {
      const parsedData: Record<string, any[]> = JSON.parse(jsonString);
      const tables = this.dbEngine.tables;

      await this.dbEngine.transaction('rw', tables, async () => {
        for (const table of tables) {
          if (parsedData[table.name]) {
            await table.clear();
            await table.bulkPut(parsedData[table.name]);
          }
        }
      });

      console.log('[Portability] Ecosystem imported and restored successfully.');
    } catch (error) {
      console.error('[Portability] Failed to import ecosystem. Data might be corrupted.', error);
      throw new Error('[Portability] Import failed. Invalid file format or database error.');
    }
  }

  /**
   * Clears all plugin-generated data but retains OS security and AI configurations.
   * The user remains logged in, but their app-specific progress is wiped.
   */
  async softReset(): Promise<void> {
    if (!this.securityService.isVaultUnlocked()) {
      throw new Error('[Portability] Cannot perform a soft reset while the vault is locked.');
    }

    // Retrieve strictly protected tables directly from the Schema Manager
    const systemTables = this.schemaManager.systemTables;
    const tablesToClear = this.dbEngine.tables.filter(t => !systemTables.includes(t.name));

    await this.dbEngine.transaction('rw', tablesToClear, async () => {
      for (const table of tablesToClear) {
        await table.clear();
      }
    });

    console.log('[Portability] Soft reset complete. Plugin data wiped. OS state retained.');
  }

  /**
   * The Nuclear Option.
   * Destroys all databases (Main and Meta), locks the vault, and reloads the application.
   * Returns the framework to its absolute initial install state.
   */
  async factoryReset(): Promise<void> {
    console.warn('[Portability] INITIATING FACTORY RESET...');

    // 1. Lock the security gatekeeper and purge memory
    this.securityService.lockVault();

    try {
      // 2. Close and delete the main framework database
      if (this.dbEngine.isOpen()) {
        this.dbEngine.close();
      }
      await this.dbEngine.delete();

      // 3. Delete the isolated Meta Database directly via native IndexedDB API
      await new Promise<void>((resolve, reject) => {
        const req = indexedDB.deleteDatabase('ArenaMetaDb');
        req.onsuccess = () => resolve();
        req.onerror = () => reject(req.error);
        req.onblocked = () => resolve(); // Proceed even if slightly blocked
      });

      // 4. Clear any potential legacy local storage
      localStorage.clear();
      sessionStorage.clear();

      console.log('[Portability] Factory reset complete. Reloading environment...');

      // 5. Force reload to re-initialize the empty OS
      window.location.reload();
    } catch (error) {
      console.error('[Portability] Critical error during factory reset:', error);
      throw error;
    }
  }
}